name: Sync to Internet Archive

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: |
            [ia]
            type = internetarchive
            access_key_id = ${{ secrets.IA_ACCESS_KEY }}
            secret_access_key = ${{ secrets.IA_SECRET_KEY }}
          disable_base64: true

      - name: Sync Entire Workspace to Internet Archive
        run: |
          rclone sync . ia:lexo-shqip-archive/ --progress \
            --exclude ".git/**" \
            --exclude ".github/**" \
            --exclude ".gitignore" \
            --exclude ".gitattributes" \
            --exclude "README.md" \
            --exclude "TODO.md" \
            --exclude "missing.md"
